const test = [
    {backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    id: 475557,
    original_title: "Joker",
    overview: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    title: "Joker"},
    {backdrop_path: "/2jSwNd2dYBetFq2922olNES2yzj.jpg",
    id: 47002,
    original_title: "ラブレター",
    overview: "When exchanging letters two women discover new things about a deceased man they used to know.",
    poster_path: "/e5lkke4fKEZNfl28gCOe6MrAjhA.jpg",
    title: "Love Letter"
    },
    {id: 84111,
    backdrop_path: "/gYULvXs45yTcYpTBrPk1GSRZTMh.jpg",
    overview: "Adolescence is like a heavy rain. Even though you catch a cold from it, you still look forward to experiencing it once again. Ko-Teng has several close friends who had a crush on Shen Chia-Yi. Those friends of Ko's thus moved in unison from Ching Chengs junior high school straight into the senior high school division in pursuit of her. Naughty in nature, Ko was ordered by their homeroom teacher to sit in front of honor student Shen for her to keep close tabs on him. The two hadn't hit it off at first but Ko gradually fell for Shen, who was always pressuring him to study hard. On the other hand, Shen became impressed by the contrasting values Ko represented. Ko started pursuing Shen but Shen remained hesitant.",
    original_title: "那些年，我們一起追的女孩",
    poster_path: "/vHWmZaITaOn3HhZermsJdSatuiN.jpg",
    title: "그 시절 우리가 좋아했던 소녀"
    },
    {backdrop_path: "/2lBOQK06tltt8SQaswgb8d657Mv.jpg",
    id: 530915,
    original_title: "1917",
    overview: "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
    poster_path: "/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    title: "1917"
    },
    {id: 313369,
    original_title: "La La Land",
    overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    title: "La La Land"},
    {backdrop_path: "/5ZoFGrFCKP0QrcfVwOIHiAwunBg.jpg",
    id: 122906,
    original_title: "About Time",
    overview: "The night after another unsatisfactory New Year party, Tim's father tells his son that the men in his family have always had the ability to travel through time. Tim can't change history, but he can change what happens and has happened in his own life – so he decides to make his world a better place... by getting a girlfriend. Sadly, that turns out not to be as easy as he thinks.",
    poster_path: "/ls6zswrOZVhCXQBh96DlbnLBajM.jpg",
    title: "About Time"},
    {id: 637,
    original_title: "Life Is Beautiful",
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    title: "인생은 아름다워",
    overview: "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    backdrop_path: "/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg"}
]

const korea = [
    {backdrop_path: "/ok2nXtQIAkQNiB9rwDQ712EVp0N.jpg",
    id: 448491,
    original_title: "Little Forest",
    overview: "A young woman leaves the city to return to her hometown in the countryside. Seeking to escape the hustle and bustle of the city, she becomes self-sufficient in a bid to reconnect with nature.",
    poster_path: "/ikAzHRcJr0wn2e6d4Vt0j5EfEvv.jpg",
    title: "리틀 포레스트"},
    {backdrop_path: "/crZlP64NPH0OFN1eMt5xtYLJ9mA.jpg",
    id: 165213,
    original_title: "New World",
    overview: "An undercover cop has his loyalties tested when the boss of the corporate gang he's spent years infiltrating dies.",
    poster_path: "/vEmpgNs0ShaljLUctzVKILrAJ6d.jpg",
    title: "신세계"},
    {backdrop_path: "/96iiyG07u4RepzW9M04B8N3JaOz.jpg",
    id: 42190,
    original_title: "클래식",
    overview: "Shy Ji-hae's friend is having problems expressing her feelings to the boy she loves, so she asks Ji-hae to write e-mails to him in her name. As the boy falls in love with her letters, Ji-hae discovers the story of her mother's romance which is remarkably similar to her own circumstances.",
    poster_path: "/sNe23Tsia9usMBN5TW2KXPJdq2K.jpg",
    title: "The Classic"},
    {backdrop_path: "/qBpup0yPaLPxmSu3TQHwchhqdFb.jpg",
    id: 38015,
    original_title: "타짜",
    overview: "A guy with a talent for cards makes his way into the dangerous world of underground gambling in this crime thriller from South Korea. Go-ni is a small-town guy with a big appetite for gambling.",
    poster_path: "/lIIGKcD9CmCYPYaCOZg3rTw0bRS.jpg",
    title: "Tazza: The High Rollers"},
    {id: 249277,
    overview: "Jjang-gu joins \"Monster,\" a violent organization at his high school. As a rite of passage, he learns a lesson about being a man while following the course.",
    title: "Wish",
    original_title: "바람",
    poster_path: "/nD5ROQV0AFFcalVokVgHP1zSUp8.jpg"},
    {backdrop_path: "/iuro932kXoNkguoRD49PlfYPHOE.jpg",
    id: 269494,
    original_title: "끝까지 간다",
    overview: "On the way to his mother’s funeral, a detective accidentally hits a person with his car. He takes the body with him and puts it into his mother’s coffin. The moment he feels relieved, he receives a call. This caller insists that he saw the detective’s hit-and-run, but instead of asking for money, he wants to know about the body’s whereabouts, leading to a do-or-die showdown of the witness and detective.",
    poster_path: "/alSvJr1pyGgEKMkEM06N9kMjSoj.jpg",
    title: "A Hard Day"},
    {backdrop_path: "/zhM9BjQ18ioRGN47HTgdw3MI1c3.jpg",
    id: 26935,
    original_title: "8월의 크리스마스",
    overview: "It’s a sweltering summer, but Jung-won, a terminally ill, thirty-something photographer, is already in the winter of his life when he begins a tentative romance with a young traffic cop who doesn’t know about his condition. Is their relationship doomed before it even begins?",
    poster_path: "/vCRcrz5zuQ9d8lgM3oEmgIqEe6b.jpg",
    title: "Christmas in August"}
]

export const koreaMovie = korea;
export const recomendMovie = test;