const recomend = [
    {id: 637,
    original_title: "Life Is Beautiful",
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    title: "인생은 아름다워",
    overview: "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    backdrop_path: "/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg"},    
    {id: 47002,
    original_title: "ラブレター",
    overview: "When exchanging letters two women discover new things about a deceased man they used to know.",
    backdrop_path: "/2jSwNd2dYBetFq2922olNES2yzj.jpg",
    poster_path: "/e5lkke4fKEZNfl28gCOe6MrAjhA.jpg",    
    title: "Love Letter"},
    {id: 313369,
    original_title: "La La Land",
    overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop_path: "/qJeU7KM4nT2C1WpOrwPcSDGFUWE.jpg",
    title: "La La Land"},
    {id: 244786,
    original_title: "Whiplash",
    overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",    
    poster_path: "/6uSPcdGNA2A6vJmCagXkvnutegs.jpg",
    title: "Whiplash",
    backdrop_path: "/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg"},
    {id: 122906,
    backdrop_path: "/5ZoFGrFCKP0QrcfVwOIHiAwunBg.jpg",
    original_title: "About Time",
    overview: "The night after another unsatisfactory New Year party, Tim's father tells his son that the men in his family have always had the ability to travel through time. Tim can't change history, but he can change what happens and has happened in his own life – so he decides to make his world a better place... by getting a girlfriend. Sadly, that turns out not to be as easy as he thinks.",
    poster_path: "/ls6zswrOZVhCXQBh96DlbnLBajM.jpg",
    title: "About Time"} ,
    {id: 84111,
    backdrop_path: "/gYULvXs45yTcYpTBrPk1GSRZTMh.jpg",
    overview: "Adolescence is like a heavy rain. Even though you catch a cold from it, you still look forward to experiencing it once again. Ko-Teng has several close friends who had a crush on Shen Chia-Yi. Those friends of Ko's thus moved in unison from Ching Chengs junior high school straight into the senior high school division in pursuit of her. Naughty in nature, Ko was ordered by their homeroom teacher to sit in front of honor student Shen for her to keep close tabs on him. The two hadn't hit it off at first but Ko gradually fell for Shen, who was always pressuring him to study hard. On the other hand, Shen became impressed by the contrasting values Ko represented. Ko started pursuing Shen but Shen remained hesitant.",
    original_title: "那些年，我們一起追的女孩",
    poster_path: "/vHWmZaITaOn3HhZermsJdSatuiN.jpg",
    title: "그 시절 우리가 좋아했던 소녀"},
    {id: 13,
    backdrop_path: "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg",
    original_title: "Forrest Gump",
    overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    poster_path: "/h5J4W4veyxMXDMjeNxZI46TsHOb.jpg",
    title: "Forrest Gump"}
]

const recomend2nd = [
    {id: 10637,
    backdrop_path: "/cMUReq46MSz6WWsdW1Gu8oecJlc.jpg",
    original_title: "Remember the Titans",
    overview: "After leading his football team to 15 winning seasons, coach Bill Yoast is demoted and replaced by Herman Boone – tough, opinionated and as different from the beloved Yoast as he could be. The two men learn to overcome their differences and turn a group of hostile young men into champions.",
    poster_path: "/tzbFc3nOeuJnuPQhQ08k8eLImu5.jpg",
    title: "Remember the Titans"},
    {id: 38,
    backdrop_path: "/ibw3MvF2GLHVcPJd2PDtOQcMDPq.jpg",
    original_title: "Eternal Sunshine of the Spotless Mind",
    overview: "Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.",
    poster_path: "/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    title: "Eternal Sunshine of the Spotless Mind"},
    {id: 475557,
    backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    original_title: "Joker",
    overview: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    title: "Joker"},
    {id: 530915,
    backdrop_path: "/2lBOQK06tltt8SQaswgb8d657Mv.jpg",
    original_title: "1917",
    overview: "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
    poster_path: "/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    title: "1917"},
    {id: 587289,
    backdrop_path: "/dRW58Pa2cg4OYfdCxskB5xR3ki6.jpg",
    original_title: "Loving Vincent: The Impossible Dream",
    overview: "A 60 minute documentary detailing the journey it took two passionate filmmakers to achieve their impossible dream, creating the world's first fully painted feature film.",
    poster_path: "/3otJ4tVumhmkd3PXFxyaTcXnYfn.jpg",
    title: "Loving Vincent: The Impossible Dream"},
    {id: 281957,
    backdrop_path: "/nMfH0LMMFk2ovyURkYvyTI99nSo.jpg",
    original_title: "The Revenant",
    overview: "In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.",
    poster_path: "/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
    title: "The Revenant"},
    {id: 27205,
    backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    original_title: "Inception",
    overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    title: "Inception"}
]

const korea = [
    {id: 448491,
    backdrop_path: "/ok2nXtQIAkQNiB9rwDQ712EVp0N.jpg",
    original_title: "Little Forest",
    overview: "A young woman leaves the city to return to her hometown in the countryside. Seeking to escape the hustle and bustle of the city, she becomes self-sufficient in a bid to reconnect with nature.",
    poster_path: "/ikAzHRcJr0wn2e6d4Vt0j5EfEvv.jpg",
    title: "리틀 포레스트"},
    {id: 31850,
    backdrop_path: "/nMxucwkm4dAT7kfxV98dXqs6P0w.jpg",
    original_title: "똥파리",
    overview: "Sang-hoon is a lowlife gangster, a debt collector exercising thuggish ways to collect his money. The recipient of nothing but anger since his childhood, he expresses himself through violence. When he finally encounters someone who can stand up to him, feisty school-girl Yoon-hee they become unlikely friends.",
    poster_path: "/cfqcOlxWKO6mTOiZWujiDKQ0Adu.jpg",
    title: "Breathless"},    
    {id: 165213,
    backdrop_path: "/crZlP64NPH0OFN1eMt5xtYLJ9mA.jpg",
    original_title: "New World",
    overview: "An undercover cop has his loyalties tested when the boss of the corporate gang he's spent years infiltrating dies.",
    poster_path: "/vEmpgNs0ShaljLUctzVKILrAJ6d.jpg",
    title: "신세계"},
    {id: 38015,
    backdrop_path: "/qBpup0yPaLPxmSu3TQHwchhqdFb.jpg",
    original_title: "타짜",
    overview: "A guy with a talent for cards makes his way into the dangerous world of underground gambling in this crime thriller from South Korea. Go-ni is a small-town guy with a big appetite for gambling.",
    poster_path: "/lIIGKcD9CmCYPYaCOZg3rTw0bRS.jpg",
    title: "Tazza: The High Rollers"},    
    {id: 42190,
    backdrop_path: "/96iiyG07u4RepzW9M04B8N3JaOz.jpg",    
    original_title: "클래식",
    overview: "Shy Ji-hae's friend is having problems expressing her feelings to the boy she loves, so she asks Ji-hae to write e-mails to him in her name. As the boy falls in love with her letters, Ji-hae discovers the story of her mother's romance which is remarkably similar to her own circumstances.",
    poster_path: "/sNe23Tsia9usMBN5TW2KXPJdq2K.jpg",
    title: "The Classic"},    
    {id: 269494,
    backdrop_path: "/iuro932kXoNkguoRD49PlfYPHOE.jpg",
    original_title: "끝까지 간다",
    overview: "On the way to his mother’s funeral, a detective accidentally hits a person with his car. He takes the body with him and puts it into his mother’s coffin. The moment he feels relieved, he receives a call. This caller insists that he saw the detective’s hit-and-run, but instead of asking for money, he wants to know about the body’s whereabouts, leading to a do-or-die showdown of the witness and detective.",
    poster_path: "/alSvJr1pyGgEKMkEM06N9kMjSoj.jpg",
    title: "A Hard Day"},
    {id: 249277,
    overview: "Jjang-gu joins \"Monster,\" a violent organization at his high school. As a rite of passage, he learns a lesson about being a man while following the course.",
    title: "Wish",
    original_title: "바람",
    poster_path: "/nD5ROQV0AFFcalVokVgHP1zSUp8.jpg"}
]

export const recomendMovie = recomend;
export const recomend2ndMovie = recomend2nd
export const koreaMovie = korea;